# Generated by Django 4.2.4 on 2023-08-29 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название раздела')),
                ('description', models.TextField(max_length=500, verbose_name='Описание раздела')),
            ],
        ),
        migrations.AlterField(
            model_name='lotimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото лота'),
        ),
        migrations.AddField(
            model_name='lot',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lot.lotsection', verbose_name='Раздел'),
        ),
    ]
