# Generated by Django 4.2.4 on 2023-09-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0003_alter_lot_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='starting_price',
            field=models.FloatField(default=0, verbose_name='Начальная цена'),
        ),
        migrations.AlterModelTable(
            name='lot',
            table='lots',
        ),
    ]
