# Generated by Django 4.2.4 on 2023-09-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0004_lot_starting_price_alter_lot_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание лота'),
        ),
    ]
