# Generated by Django 4.2.4 on 2023-09-20 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lot', '0005_alter_lot_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'verbose_name': 'лот', 'verbose_name_plural': 'лоты'},
        ),
        migrations.AddField(
            model_name='lot',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lot',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
