# Generated by Django 4.2.4 on 2023-10-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0007_alter_lotsection_options_alter_lot_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'permissions': [('can_mark_as_suspicious', 'Может помечать как подозрительное')], 'verbose_name': 'лот', 'verbose_name_plural': 'лоты'},
        ),
    ]
