# Generated by Django 4.2.4 on 2023-10-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0010_lotcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotcomment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AddField(
            model_name='lotcomment',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
