# Generated by Django 4.2.4 on 2023-10-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0011_alter_lotcomment_options_lotcomment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotcomment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
