# Generated by Django 4.2.4 on 2023-10-07 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lot', '0012_alter_lotcomment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
