# Generated by Django 4.2.4 on 2023-10-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0013_lot_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='highest_price',
            field=models.FloatField(default=0, verbose_name='Наибольшая цена'),
        ),
    ]
