# Generated by Django 4.2.4 on 2023-10-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0015_lot_current_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Продано'),
        ),
    ]
